apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutumchart.fullname" . }}
  labels:
    {{- toYaml .Values.podLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.podLabels | nindent 4 }}
