apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
spec:
  template:
    spec:
      containers:
      - name: whalesay
        image: docker/whalesay
        command: ["cowsay", "This is a Kubernetes Job to say Hello UoPeople! Hope you Enjoy!"]
      restartPolicy: Never
  backoffLimit: 4